local _M = {}

local err_table = {
    ERROR_NONE = 0,
    ERROR_JSON_WRONG = 1,
    ERROR_PARAMS_WRONG = 2,
    ERROR_HTTP_HEADER_LACKED = 3,
    ERROR_HTTP_HEADER_DEV_TYPE = 4,
    ERROR_HTTP_TOKEN_NONE = 5,
    ERROR_HTTP_TOKEN = 6,
    ERROR_HTTP_TOKEN_EXPIRED = 7,
    ERROR_API_NOT_SUPPORT = 8,


    --
    --user
    --
    ERROR_USER_PASSWORD_WRONG = 100,
    ERROR_USER_NAME_WRONG = 101,
    ERROR_USER_NAME_OR_PASSWORD_WRONG = 102,
    ERROR_USER_TOKEN_EXPIRED = 103,
    ERROR_USER_LOGIN_FAILED = 104,
    ERROR_USER_ID_INVALID = 105,
    ERROR_USER_PASSWORD_NEW_OLD_SAME = 106,
    ERROR_USER_PASSWORD_CHANGE_FAILED = 107,
    ERROR_USER_NO_EXISTS = 108,
    ERROR_USER_PERMISSION_REFUSE = 109,
    ERROR_USER_LIST_GET_FAILED = 110,
    ERROR_USER_UPDATE_FAILED = 111,
    ERROR_USER_PASSWORD_RESET_FAILED = 112,
    ERROR_USER_LIST_WITH_ORGANIZATION_FAILED = 113,
    ERROR_USER_IMPORT_FAILED = 114,
    ERROR_USER_INFO_GET_FAILED = 115,
    ERROR_USER_ERP_MSG_RECEIVE_SET_FAILED = 116,


    --
    --project
    --
    ERROR_PROJ_LIST_GET_FAILED = 300,
    ERROR_PROJ_DATA_INVALID = 301,
    ERROR_PROJ_NO_EXISTS = 302,
    ERROR_PROJ_UPDATE_FAILED = 303,
    ERROR_PROJ_GLOBAL_CONFIG_GET_FAILED = 304,
    ERROR_PROJ_IMPORT_FAILED = 305,
    ERROR_PROJ_LINK_PIC_DESCRIBE_GET_FAILED = 306,
    ERROR_PROJ_INFO_UPDATE_FAILED = 307,
    ERROR_PROJ_FINED_LIST_GET_FAILED = 308,
    ERROR_PROJ_FINED_LIST_FILE_GEN_FAILED = 309,
    ERROR_PROVINCE_FINED_LIST_FILE_GEN_FAILED = 310,
    ERROR_PROJ_PIC_ADD_FLAG_SET_FAILED = 311,
    --
    --link
    --
    ERROR_LINK_GET_FAILED = 500,
    ERROR_LINK_GEN_FAILED = 501,
    ERROR_LINK_GEN_NOT_ALLOWED = 502,
    ERROR_LINK_ID_INVALID = 503,
    ERROR_LINK_ID_DUPLICATE = 504,
    ERROR_LINK_SUBMIT_FAILED = 505,
    ERROR_LINK_NO_EXISTS = 506,
    ERROR_LINK_PIC_INFO = 507,
    ERROR_LINK_INFO = 508,
    ERROR_LINK_SUBMIT_FAIL = 509,
    ERROR_LINK_CHANGE_NOT_ALLOWED = 510,
    ERROR_LINK_REVIEW_FAILED = 511,
    ERROR_LINK_LIST_GET_FAILED = 512,
    ERROR_LINK_RECOD_LIST_GET_FAILED = 513,
    ERROR_LINK_ADD_FAILED = 514,
    ERROR_LINK_ID_NO_EXISTS = 515,
    ERROR_LINK_REVIEWED_NO_PASS = 516,
    ERROR_REVIEW_NOT_LINK_FAILED = 517,
    ERROR_LINK_REVIEW_STATUS_RESET_FAILED = 518,
    ERROR_LINK_REVIEW_STATUS_RESET_GET_FAILED = 519,
    --fixed by zhangjieqiong for gaizao 20200520
    --fixed by zhangjieqiong for reset list 20200811

    --fine
    ERROR_LINK_FINED_ITEM_GET_FAILED = 550,
    ERROR_LINK_FINED_ALREADY = 551,
    ERROR_LINK_FINE_FAILED = 552,
    ERROR_LINK_FINE_BACKUP_FAILED = 553,
    ERROR_LINK_FINED_TWICE = 554,

    --meeting
    ERROR_MEET_INFO = 600,
    ERROR_MEET_LIST_GET_FAILED = 601,
    ERROR_PIC_SOURCE = 602,
    ERROR_MEET_INFO_ALREADY_EXISTS = 603,

    --organization
    --
    ERROR_ORGA_LIST_GET_FAILED = 700,

    --
    --user operation log
    --
    ERROR_LOG_LIST_GET_FAILED = 10000,


    --
    --android update
    --
    ERROR_ANDROID_UPDATE_CHECK_FAILED = 20000,
    ERROR_ANDROID_APP_VERSION_TOO_LOWER = 20001,


    --
    --push message
    --
    ERROR_MESSAGE_LIST_GET_FAILED = 30000,
    ERROR_MESSAGE_SEND_FAILED = 30001
}

function _M.get_error(name)
    return err_table[name]
end

return _M
